name: Test and deploy

on:
  push:

jobs:
  static_code_analysis:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Detekt
        run: ./gradlew detekt

      - name: Ktlint
        run: ./gradlew ktlintCheck

  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Unit tests
        run: ./gradlew test